[package]
name = "ratchet-pawl"
version = "0.1.0"
edition = "2021"

[profile.dev]
incremental = true

[dependencies]
rocket = {version="0.5.1", features=["json"]}
serde = { version = "1.0.214", features = ["derive"] }
serde_json = "1.0.133"
lazy_static = "1.5.0"
redb = "2.3.0"
